// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkDltTMpyKwDJxKSep777PTyFs7Ia40do',
    appId: '1:66949937803:web:675c26e8942dca0ec4728e',
    messagingSenderId: '66949937803',
    projectId: 'bus-tracking-51437',
    authDomain: 'bus-tracking-51437.firebaseapp.com',
    storageBucket: 'bus-tracking-51437.firebasestorage.app',
    measurementId: 'G-NLLDFFLDT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7996wtpGqzcJaBgix_sM9sXvrSvcHbcc',
    appId: '1:66949937803:android:53ac6d1ebb002d09c4728e',
    messagingSenderId: '66949937803',
    projectId: 'bus-tracking-51437',
    storageBucket: 'bus-tracking-51437.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXmCj1zNLw4cuu-7c34AqrG7Jz2kPyYfo',
    appId: '1:66949937803:ios:a09dd3acd81d172ac4728e',
    messagingSenderId: '66949937803',
    projectId: 'bus-tracking-51437',
    storageBucket: 'bus-tracking-51437.firebasestorage.app',
    iosBundleId: 'com.example.driverSide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXmCj1zNLw4cuu-7c34AqrG7Jz2kPyYfo',
    appId: '1:66949937803:ios:a09dd3acd81d172ac4728e',
    messagingSenderId: '66949937803',
    projectId: 'bus-tracking-51437',
    storageBucket: 'bus-tracking-51437.firebasestorage.app',
    iosBundleId: 'com.example.driverSide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkDltTMpyKwDJxKSep777PTyFs7Ia40do',
    appId: '1:66949937803:web:7f4f41956bedae47c4728e',
    messagingSenderId: '66949937803',
    projectId: 'bus-tracking-51437',
    authDomain: 'bus-tracking-51437.firebaseapp.com',
    storageBucket: 'bus-tracking-51437.firebasestorage.app',
    measurementId: 'G-M4HYN77DHS',
  );
}
